main: train_exbm.py
experiment_iterations: 3
dataset: bird
pretrained: pretrained/model_base_caption_capfilt_large.pth

# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0

image_size: 384
batch_size: 32

# optimizer
weight_decay: 0.05
init_lr: 3e-5
min_lr: 0
lr_decay_rate: 0.9
max_epoch: 100
warmup_lr: 1e-6
warmup_steps: 50

num_classes: 200
sample: False
num_beams: 3
max_decode_length: 50
min_decode_length: 20
use_cross_attn: True
fixed_caps: False
fixed_vit: False
tied_encoder: False
lambda: 0.1
temperature: 100.0
temperature_annealing: exp